<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage/MasterPage.master" AutoEventWireup="true" CodeFile="RequistionLIST_APRD.aspx.cs" Inherits="PROCUREMENT_RequistionLIST_APRD" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
<script src="../jquery-1.8.2.js"></script>
    <script src="../jquery.min.js"></script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">


<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
	<link href="../vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="../vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
	<!-- ================== END PAGE LEVEL STYLE ================== -->
    <asp:HiddenField ID="hdnUID" Value="0" runat="server" />
    <div class="row">
                <!-- begin col-6 -->
			    <div class="col-md-12">
			        <!-- begin panel -->
                    <div class="panel widget light-widget panel-bd-top">
                        <div class="panel-heading bordered">
                    <h3 class="panel-title"> <span class="menu-icon"> <i class="icon-pie"></i> </span> Approved Requisition! </h3>
                    <div class="vd_panel-menu">
  <div data-action="minimize" data-original-title="Minimize" data-toggle="tooltip" data-placement="bottom" class=" menu entypo-icon"> <i class="icon-minus3"></i> </div>
  <div data-action="refresh"  data-original-title="Refresh" data-toggle="tooltip" data-placement="bottom" class=" menu entypo-icon smaller-font"> <i class="icon-cycle"></i> </div>
  
  <div data-action="close" data-original-title="Close" data-toggle="tooltip" data-placement="bottom" class=" menu entypo-icon"> <i class="icon-cross"></i> </div>
</div>
<!-- vd_panel-menu --> 
                  </div>
                        <div class=" panel-body-list" style="padding:10px">

                <div class="row">
                                <div class="col-md-12" style=" text-align:right">
                                <asp:HyperLink ID="HyperLink2" NavigateUrl="~/PROCUREMENT/Requisition.aspx" runat="server">Add New Requisition</asp:HyperLink>
                                </div>
                             </div>
                <div class="row col-lg-12">
                                                
                                                 <div class="table-responsive" id="dvList" >
                                <table id="data-table" class="table table-striped table-bordered" >
                                
                                </table>
                            </div>

                                            </div>
</div>
                    </div>
                    <!-- end panel -->
                </div>
                </div>



              <!-- Modal Quotation -->
                  <div class="modal fade" id="modalQuotation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" >
                      <div class="modal-content" style="width:900px">
                        <div class="modal-header vd_bg-blue vd_white">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
                          <h4 class="modal-title" id="myModalLabel">Quotation</h4>
                        </div>
                        <div class="modal-body" > 
                        	
                            <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label class="col-md-12 control-label">Req. No.</label>
                                    
                                    <div class="col-md-12" id="dvSOID">
                                        
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label class="col-md-12 control-label">Generated By</label>
                                    
                                    <div class="col-md-12" id="dvGeneratedByQT">
                                      
                                    </div>
                                </div>
                            </div>

                            


                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label class="col-md-12 control-label">Approved By</label>
                                    
                                    <div class="col-md-12" id="dvApprovedByQT">
                               


                                    </div>
                                </div>
                            </div>

                           

                            
                        </div>


                            <div class="row">
                                <div class="col-lg-12 table-responsive" id="dvListRequisition">
                                   

                                    <%--<input type="button" value="" class="fa-plus-square" onclick="addRow();SumDbCr();"/>--%>
                                </div>
                            </div>
                            
                            
                             <div class="row"><div class="col-lg-12" >
                             <div class="col-lg-5">
                             <input type="button" id="Button2" class="btn btn-info" value="Email to Supplier" onclick="SupplierEmail();" />
                             </div>
                             <div class="col-lg-4" style="text-align:right">
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Supplier</label>
                                    
                                    <div class="col-md-9">
                                <asp:DropDownList ID="ddlSupplier" CssClass="form-control" runat="server" DataSourceID="SqlDataSource1" 
                                            DataTextField="SupplierTitle" DataValueField="SupplierID">
                                </asp:DropDownList>


                                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                                            ConnectionString="<%$ ConnectionStrings:Con %>" 
                                            SelectCommand="SELECT '0' as [SupplierID],'Select Supplier' as [SupplierTitle] FROM [Supplier] union SELECT [SupplierID], [SupplierTitle] FROM [Supplier] WHERE ([ISDELETE] = @ISDELETE)">
                                            <SelectParameters>
                                                <asp:Parameter DefaultValue="0" Name="ISDELETE" Type="Int32" />
                                            </SelectParameters>
                                        </asp:SqlDataSource>


                                    </div>
                                </div>
                            </div>
                            <%-- <input type="button" id="btnClear" class="btn btn-danger btn-sm" value="Clear Form" onclick="ClearForm();" />--%>
                             <div class="col-lg-3">
                             <input type="button" id="btnSave" class="btn btn-success btn-block" value="Add Quotation" onclick="SaveQuotation();" />
                             </div>
                             </div></div>

                             <div class="table-responsive" id="dvQuotation" >
                                
                            </div>
                          
                        </div>
                        <div class="modal-footer background-login">
                          <!--<button type="button" class="btn vd_btn vd_bg-grey" data-dismiss="modal">No</button>
                          <button type="button" class="btn vd_btn vd_bg-green" onclick="ProcessOrder();">Yes</button>-->
                        </div>
                      </div>
                      <!-- /.modal-content --> 
                    </div>
                    <!-- /.modal-dialog --> 
                  </div>
                  <!-- /.modal --> 
              <!-- Modal Quotation -->



              <!-- Modal Purchase Order -->
                  <div class="modal fade" id="modalPO" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" >
                      <div class="modal-content" style="width:900px">
                        <div class="modal-header vd_bg-blue vd_white">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
                          <h4 class="modal-title" id="H1">Purchase Order</h4>
                        </div>
                        <div class="modal-body" > 
                        	
                           <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label class="col-md-12 control-label">Req. No.</label>
                                    
                                    <div class="col-md-12" id="dvReqNoPO">
                                        
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label class="col-md-12 control-label">Generated By</label>
                                    
                                    <div class="col-md-12" id="dvGeneratedByPO">
                                      
                                    </div>
                                </div>
                            </div>

                            


                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label class="col-md-12 control-label">Approved By</label>
                                    
                                    <div class="col-md-12" id="dvApprovedByPO">
                               


                                    </div>
                                </div>
                            </div>

                           

                            
                        </div>


                            <div class="row">
                                <div class="col-lg-12 table-responsive" id="dvListPO">
                                   

                                    <%--<input type="button" value="" class="fa-plus-square" onclick="addRow();SumDbCr();"/>--%>
                                </div>
                            </div>
                            
                            
                             <div class="row"><div class="col-lg-12" style="text-align:right">
                             <div class="col-lg-5">
                            <div class="form-group">
                                    <label class="col-md-3 control-label">PO Date</label>
                                    
                                    <div class="col-md-9">
                                    <div class="input-group">
                                       <input type="text" class="width-100" id="datepicker-autoClose" placeholder="Select Date" />
                                       <span class="input-group-addon" id="datepicker-icon-trigger-PV" data-datepicker="#datepicker-autoClose"><i class="fa fa-calendar"></i></span>
                                       </div>
                                    </div>
                                </div>
                             </div>
                             <div class="col-lg-4" style="text-align:right">
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Supplier</label>
                                    
                                    <div class="col-md-9">
                                <asp:DropDownList ID="ddlSupplierPO" CssClass="form-control" runat="server" DataSourceID="SqlDataSource1" 
                                            DataTextField="SupplierTitle" DataValueField="SupplierID">
                                </asp:DropDownList>



                                    </div>
                                </div>
                            </div>
                            <%-- <input type="button" id="btnClear" class="btn btn-danger btn-sm" value="Clear Form" onclick="ClearForm();" />--%>
                             <div class="col-lg-3">
                             <input type="button" id="Button1" class="btn btn-success btn-block" value="Add PO" onclick="SavePO();" />
                             </div>
                             </div></div>

                             <div class="table-responsive" id="dvPOList" >
                                
                            </div>
                          
                        </div>
                        <div class="modal-footer background-login">
                          <!--<button type="button" class="btn vd_btn vd_bg-grey" data-dismiss="modal">No</button>
                          <button type="button" class="btn vd_btn vd_bg-green" onclick="ProcessOrder();">Yes</button>-->
                        </div>
                      </div>
                      <!-- /.modal-content --> 
                    </div>
                    <!-- /.modal-dialog --> 
                  </div>
                  <!-- /.modal --> 
              <!-- Modal PO -->



                      <script src="../js/jquery-1.9.1.min.js"></script>
		<script src="../js/bootstrap.min.js"></script>
            <script type="text/javascript" src='../AAUI/plugins/jquery-ui/jquery-ui.custom.min.js'></script>
    <script src="RequistionLIST_APRD.js" type="text/javascript"></script>


     <script type="text/javascript">

         $("#datepicker-autoClose").datepicker({ dateFormat: 'm/dd/yy' });
         $('[data-datepicker]').click(function (e) {
             var data = $(this).data('datepicker');
             $(data).focus();
         });
    </script>
</asp:Content>

